# ParticleX Configuration
# https://github.com/theme-particlex/hexo-theme-particlex

# Avatar image
avatar: https://cloud.waveyo.cn/Services/websites/blog/images/avatar.jpg

# Home page background image
background:
    - https://cloud.waveyo.cn/Services/websites/blog/images/background.png
    - https://cloud.waveyo.cn/Services/images/background/background1.jpg
    - https://cloud.waveyo.cn/Services/images/background/background2.jpg
    - https://cloud.waveyo.cn/Services/images/background/background3.jpg
    - https://cloud.waveyo.cn/Services/images/background/background4.jpg
    - https://cloud.waveyo.cn/Services/images/background/background5.jpg
    - https://cloud.waveyo.cn/Services/images/background/background6.jpg
    - https://cloud.waveyo.cn/Services/images/background/background7.jpg
    - https://cloud.waveyo.cn/Services/images/background/background8.jpg
    - https://cloud.waveyo.cn/Services/images/background/background9.jpg
    - https://cloud.waveyo.cn/Services/images/background/background10.jpg
# Loading image
loading: https://cloud.waveyo.cn/Services/websites/blog/images/loading.gif

# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

# Main menu navigation
menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags
    友情链接:
        enable: true
        name: link
        theme: solid
        link: /links
    RSS:
        name: rss
        theme: solid
        link: /rss.xml
    Atom:
        name: atom
        theme: solid
        link: /atom.xml

links:
  - name: "离子的杂货铺"
    url: "https://blog.loveak.top"
    Author:
    desc: "Author：Plasmon222"
  - name: "玺朽导航"
    url: "https://lonelymeko.top/"
    Author: 
    desc: "Author：玺朽"


# Side info card
card:
    enable: true
    description: |
    
    iconLinks: 
        Home:
            name: house
            theme: solid
            link: http://home.waveyo.cn
        GitHub:
            name: github
            theme: brands
            link: https://github.com/WavesMan
        BiliBili:
            name: bilibili
            theme: brands
            link: https://space.bilibili.com/478191001
        
    friendLinks: 
        #GitHub: https://github.com/WavesMan 

# Footer info
footer:
    since: 2024
    # Customize the server domain name ICP
    ICP:
        enable: true
        code: 皖ICP备2025078205号
        link: https://beian.miit.gov.cn/
    PSR: 
        enable: true
        code: 皖公网安备34040002000514号
        link: https://beian.mps.gov.cn/#/query/webSearch?code=


# Polyfill
# https://polyfill.io
polyfill:
    enable: true
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: github-dark-dimmed-min

# Mermaid
# https://mermaid.js.org
mermaid:
    enable: true
    theme: default

# KaTeX math rendering
math:
    enable: false

# Image preview
preview:
    enable: true

# Article encryption
crypto:
    enable: false

# Search
search:
    enable: false

# giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang:

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy

# Waline
# https://github.com/walinejs/waline
waline:
    enable: true
    serverURL: https://commentaries.waveyo.cn/
        # Waline 服务器地址网址，您应将其设置为自己的链接
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
    commentCount: true # 如果为false，评论计数将只显示在文章页面，而不显示在主页上
    pageview: true 
        # 页面浏览量计数，注意：不能同时启用 `waline.pageview` 和 `leancloud_visitors` 两项功能。
    dark: auto # 自动切换深色模式
    emoji: # 自定义 emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # 评论信息，有效的元信息包括昵称、邮件和链接
        - nick
        - mail
        - link
    requiredMeta: # 设置所需的元字段，例如 [nick] | [nick, mail]
        - nick
        - mail
        - link
    lang: zh-CN
        # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # 字数限制，设置为 0 时无限制
    login: enable # 是否启用登录，可从 'enable', 'disable' 和 'force' 选择
    pageSize: 10 # 每页评论

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: false
    envID:
    region:
    path: location.pathname
    lang:

description: |
    Normal _Italic_ **Strong**
